---
output:
  html_document:
    #css: !expr here::here("assets", "styles_pjp.css") 
    css: assets/styles_pjp.css
    #theme: cerulean  #o flatly(gris)  united (naranja) spacelab(azulito) o yeti o faltly o sandstone
    #highlight: kate 
    self_contained: yes
    number_sections: no
    #includes:
       #in_header: google-analytics.html
    #toc: true
    #toc_float: true
    #code_folding: show
    #self_contained: TRUE
---

<br>

<div class = "blue">
**Tutoriales**: en esta sección iré subiendo los tutoriales conforme los vaya actualizando. Se supone que algún día juntaré todos los tutoriales en un `bookdown`, una especie de libro electrónico hecho con R; de momento, para la web del curso prefiero el formato actual. Todas los tutoriales están hechos con R; de hecho, una de las cosas que has de aprender durante el curso es a hacer ficheros parecidos a estos tutoriales, ya que los proyectos del curso tendrás que presentarlos en este formato. Verás que es sencillo.
</div>

<br><br>

# Tutoriales

--------------------------


- [Prefacio](./tutoriales/tt_00_prefacio.html){target="_blank"}

- [Tutorial 01: Introducción](./tutoriales/tt_01_introduccion.html){target="_blank"} 

- [Tutorial 02: Workflow](./tutoriales/tt_02_primeros-pasos-con-R.html){target="_blank"} 

- [Tutorial 03: R base](./tutoriales/tt_03_R-base.html){target="_blank"} 

- [Tutorial 04: Cargar datos](./tutoriales/tt_04_cargar_datos.html){target="_blank"} 

- [Tutorial 05: Data munging](./tutoriales/tt_05_data-munging.html){target="_blank"} 

- [Tutorial 06: ggplot2](./tutoriales/tt_06_ggplot2.html){target="_blank"} 

- [Tutorial 07: Rmarkdown](./tutoriales/tt_07_Rmarkdown.html){target="_blank"} 

- [Tutorial 08: Tablas con Rmarkdown](./tutoriales/tt_08_tablas-Rmarkdown.html){target="_blank"} 

- [Tutorial 09: Introducción a GIS con R](./tutoriales/tt_09_GIS-con-R.html){target="_blank"} 

- [Tutorial 10: Un poco de EDA y modelos](./tutoriales/tt_10_EDA.html){target="_blank"} 



<br><br>


<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>
